### ISSUE TITLE
Binder node "binder" for waydroid not found

### ISSUE THREAD

**Issue by aindriu80** [waydroid/waydroid#590]
**Describe the bug**
Can't install Wayroid

```
Waiting for waydroid container service...
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
Binder node "binder" for waydroid not found
```
**Screenshots**

![2022-11-14_09-30](https://user-images.githubusercontent.com/8885837/201624622-1d6c2881-59b6-465e-a31e-7953dec80712.png)

![2022-11-14_09-31](https://user-images.githubusercontent.com/8885837/201624965-04fdd526-4ee2-4a78-95ba-1f7b191f2cd7.png)

![2022-11-14_09-31_1](https://user-images.githubusercontent.com/8885837/201624984-92d86db6-abfe-41bc-bdc7-52f67762f3d5.png)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: Pop 22.04
 - GPU: AMD Radeon™ RX 6600
 - Kernel version:  6.0.6-76060006-generic
 - Host mesa version:  ?
 - Desktop: GNOME 42.3.1 

**Additional context**
I've tried solutions on other threads but noting worked.

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of 
 `(051925) [09:23:18] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(051925) [09:23:18] Failed to load binder driver
(051925) [09:23:18] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(051960) [09:23:30] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(051960) [09:23:30] Failed to load binder driver
(051960) [09:23:30] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(052272) [09:24:13] ERROR: Action "init" needs root access
(052272) [09:24:13] See also: <https://github.com/waydroid>
(052272) [09:24:13] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 52, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 18, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(052305) [09:24:22] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(052305) [09:24:22] Failed to load binder driver
(052305) [09:24:22] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(052305) [09:24:22] ERROR: Binder node "binder" for waydroid not found
(052305) [09:24:22] See also: <https://github.com/waydroid>
(052305) [09:24:22] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 53, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 101, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 93, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(055005) [09:28:02] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(055005) [09:28:02] Failed to load binder driver
(055005) [09:28:02] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(055709) [09:30:49] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(055709) [09:30:49] Failed to load binder driver
(055709) [09:30:49] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
(055709) [09:30:49] ERROR: Binder node "binder" for waydroid not found
(055709) [09:30:49] See also: <https://github.com/waydroid>
(055709) [09:30:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 53, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 101, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 93, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(056767) [09:34:16] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(056767) [09:34:16] *** output passed to waydroid stdout, not to this log ***
`

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
Produces the following :-
```
ERROR: WayDroid is not initialized, run "waydroid init"
[09:35:10] ERROR: Action "init" needs root access
[09:35:10] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
Waydroid init produces the following :-

`[09:35:10] ERROR: Action "init" needs root access
[09:35:10] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
`

sudo waydroid init

`[09:38:35] Failed to load binder driver
[09:38:35] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.6-76060006-generic
[09:38:35] ERROR: Binder node "binder" for waydroid not found
[09:38:35] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
`

**Comment by hdfsyu** [comment]
I'm having the same problem too...

**Comment by aleasto** [comment]
Added PopOS install instructions

**Comment by smith558** [comment]
Same issue on Ubuntu 22.10

**Comment by foxhacker0000** [comment]
same issue in Ubuntu 22.04

**Comment by Walker088** [comment]
I had the same issue on my Ubuntu 22.04 with kernel version 6.2.7-060207-generic
Then I see this [thread](https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install) on reddit and the provided repo, [anbox-modules](https://github.com/choff/anbox-modules) solved it on my machine

**Comment by smith558** [comment]
@aleasto perhaps this issue should be re-opened

**Comment by haipnh** [comment]
> I had the same issue on my Ubuntu 22.04 with kernel version 6.2.7-060207-generic Then I see this [thread](https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install) on reddit and the provided repo, [anbox-modules](https://github.com/choff/anbox-modules), solved it on my machine

Thank you. It works on my machine as well.
Ubuntu 22.04 - Linux kernel 5.15.

**Comment by shine-Diamond-295** [comment]
Anbox modules didnt work for me, I had to delete dkms entirely and remove all the anbox modules from /dev and install the linux-zen kernel since it comes with the binder module installed already. Ashmem isn't needed anymore according to the arch wiki. I'm running arch tho so your mileage may vary

**Comment by Jieiku** [comment]
All I had to do on Arch to get up and running with Waydroid after reading the wiki was install cage and switch to the zen kernel.

**Comment by krishnaraj** [comment]
> Added PopOS install instructions: https://docs.waydro.id/usage/install-on-desktops#popos

This section seems to be missing?

**Comment by Xses-1** [comment]
Still an issue on Popos, anbox had last push 4 years ago, and it does not install anymore, popos installation section is gone from the waydroid docs.

That sucks.

**Comment by dubwoc** [comment]
There is a forked repo with compile fixes for the latest kernel: https://github.com/choff/anbox-modules

Instructions copied from the repo:
```
git clone https://github.com/choff/anbox-modules
cd anbox-modules
sudo cp -rT ashmem /usr/src/anbox-ashmem-1
sudo cp -rT binder /usr/src/anbox-binder-1
sudo dkms install anbox-ashmem/1
sudo dkms install anbox-binder/1
sudo modprobe ashmem_linux binder_linux
```

Then run ```sudo waydroid init```

**Comment by dubwoc** [comment]
There is a forked repo with compile fixes for the latest kernel: https://github.com/choff/anbox-modules

Instructions copied from the repo:
```
git clone https://github.com/choff/anbox-modules
cd anbox-modules
sudo cp anbox.conf /etc/modules-load.d/
sudo cp 99-anbox.rules /lib/udev/rules.d/
sudo cp -rT ashmem /usr/src/anbox-ashmem-1
sudo cp -rT binder /usr/src/anbox-binder-1
sudo dkms install anbox-ashmem/1
sudo dkms install anbox-binder/1
# either reboot or give the following a go to do it without a reboot. 
sudo udevadm control --reload-rules
sudo udevadm trigger
sudo modprobe ashmem_linux binder_linux
```

I also had to switch to Wayland as I was still running X11, you can tell what you are running by doing the following in a terminal:
```echo $XDG_SESSION_TYPE```

If it says X11 you need to edit /etc/gdm3/custom.conf and set WaylandEnable=false to **true** 

Then restart the session manager: ```sudo systemctl restart gdm.service``` and when you click on the user click on the gear in the lower right to set the session to *Pop on Wayland*


Login open a terminal and give ```sudo waydroid init``` a go

I found https://github.com/casualsnek/waydroid_script to also be helpful.

**Comment by ahfauth** [comment]
@dubwoc I tried to follow your steps but I get the following errors. Any idea?

sudo dkms install anbox-ashmem/1

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j20 KERNELRELEASE=6.8.0-76060800daily20240311-generic all KERNEL_SRC=/lib/modules/6.8.0-76060800daily20240311-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-ashmem: 1 not found
Error! Bad return status for module build on kernel: 6.8.0-76060800daily20240311-generic (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.


LOG (/var/lib/dkms/anbox-ashmem/1/build/make.log ):

DKMS make.log for anbox-ashmem-1 for kernel 6.8.0-76060800daily20240311-generic (x86_64)
Mon Apr 15 06:44:48 PM -03 2024
make -C /lib/modules/6.8.0-76060800daily20240311-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-76060800daily20240311-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /var/lib/dkms/anbox-ashmem/1/build/deps.o
  CC [M]  /var/lib/dkms/anbox-ashmem/1/build/ashmem.o
/var/lib/dkms/anbox-ashmem/1/build/deps.c:6:5: warning: no previous prototype for ‘shmem_zero_setup’ [-Wmissing-prototypes]
    6 | int shmem_zero_setup(struct vm_area_struct *vma)
      |     ^~~~~~~~~~~~~~~~
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c: In function ‘ashmem_mmap’:
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c:393:23: error: assignment of read-only member ‘vm_flags’
  393 |         vma->vm_flags &= ~calc_vm_may_flags(~asma->prot_mask);
      |                       ^~
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c: In function ‘ashmem_init’:
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c:877:9: error: implicit declaration of function ‘register_shrinker’; did you mean ‘register_chrdev’? [-Werror=implicit-function-declaration]
  877 |         register_shrinker(&ashmem_shrinker);
      |         ^~~~~~~~~~~~~~~~~
      |         register_chrdev
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c: In function ‘ashmem_exit’:
/var/lib/dkms/anbox-ashmem/1/build/ashmem.c:884:9: error: implicit declaration of function ‘unregister_shrinker’; did you mean ‘unregister_chrdev’? [-Werror=implicit-function-declaration]
  884 |         unregister_shrinker(&ashmem_shrinker);
      |         ^~~~~~~~~~~~~~~~~~~
      |         unregister_chrdev
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/anbox-ashmem/1/build/ashmem.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-76060800daily20240311-generic/Makefile:1927: /var/lib/dkms/anbox-ashmem/1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-76060800daily20240311-generic'
make: *** [Makefile:12: all] Error 2

**Comment by Xses-1** [comment]
@ahfauth report it to the repo maintainers.

Also why to hell is this thread closed?

**Comment by dubwoc** [comment]
@ahfauth it is unclear if you are using the same source as I mentioned above, I am on the same kernel as you and do not have compile errors. It looks like perhaps you have installed other additional packages that are causing conflicts.

**Comment by ahfauth** [comment]
@dubwoc could it be Nvidia Drivers?

**Comment by dubwoc** [comment]
No that does not have anything to do with the nvidia drivers being installed. Are you using the source code I mentioned above? When I search for the error you are seeing it is pointing at the original source for Binder and you need the patched source I mentioned above.

**Comment by m-aljammali** [comment]
having the same issue on pop os.

**Comment by ahfauth** [comment]
@m-aljammali I am also running pop-os. No idea what is happening.

**Comment by obenchkroune** [comment]
Got it working on pop_OS! after installing the required kernel modules
https://github.com/choff/anbox-modules

**Comment by ahfauth** [comment]
@obenchkroune could you please reproduce the steps for pop-os users? Thank you!

**Comment by dantosXD** [comment]
> sudo waydroid init

This worked perfectly for me on POP-OS!

**Comment by mjonyh** [comment]
> There is a forked repo with compile fixes for the latest kernel: https://github.com/choff/anbox-modules
> 
> Instructions copied from the repo:
> 
> ```
> git clone https://github.com/choff/anbox-modules
> cd anbox-modules
> sudo cp anbox.conf /etc/modules-load.d/
> sudo cp 99-anbox.rules /lib/udev/rules.d/
> sudo cp -rT ashmem /usr/src/anbox-ashmem-1
> sudo cp -rT binder /usr/src/anbox-binder-1
> sudo dkms install anbox-ashmem/1
> sudo dkms install anbox-binder/1
> # either reboot or give the following a go to do it without a reboot. 
> sudo udevadm control --reload-rules
> sudo udevadm trigger
> sudo modprobe ashmem_linux binder_linux
> ```
> 
> I also had to switch to Wayland as I was still running X11, you can tell what you are running by doing the following in a terminal: `echo $XDG_SESSION_TYPE`
> 
> If it says X11 you need to edit /etc/gdm3/custom.conf and set WaylandEnable=false to **true**
> 
> Then restart the session manager: `sudo systemctl restart gdm.service` and when you click on the user click on the gear in the lower right to set the session to _Pop on Wayland_
> 
> Login open a terminal and give `sudo waydroid init` a go
> 
> I found https://github.com/casualsnek/waydroid_script to also be helpful.

It works on archlinux

**Comment by waozixyz** [comment]
Had to follow the same instructions as @mjonyh for the latest PopOS LTS release, maybe this should be added to the waydroid documentation? would be quite useful, and seems to be easy to reproduce. It's no special case scenario, get a clean PopOS lts release, follow the instructions otherwise you get the binder error.

**Comment by mdelhaous** [comment]
https://github.com/waydroid/waydroid/issues

**Comment by Adhjie** [comment]
I have the same problem, can't installed binder_modules either with the following error: (any way to use linux zen kernel in wsl? even with get wsl in telegram to get the kernel for waydroid on wsl, the problem of binder_modules persist, I'm on ubuntu so I can't use AUR either.
NVIDIA 1650Ti, still not sure if I should install or not since CUDA guide to not install linux gpu driver, host is enough)
Logs:
;

![Image](https://github.com/user-attachments/assets/17f65e84-9ed8-4867-b376-8cd933c08a8b)

;
Telegram waydroid command:/get wsl
:
/notes

Rose (bot):
List of notes in WayDroid:
 - adb
 - add_microg
 - add_smart_dock
 - certificate_error
 - certified
 - clipboard
 - docs
 - fedora
 - fix_colors
 - gapps
 - important_logs
 - multi_windows
 - remount_rw
 - vm_swiftshader
 - wayland_session
 - what_is_waydroid
 - wpm
 - wsl
 - x11
You can retrieve these notes by using /get notename, or #notename
;
I have a question about the kernel for wsl, could anyone answer this:
>wadydroid_Kernel:
WSL needs custom kernel, so place this on "system32/lxss/tools/kernel"
1. Should I put this using this directory template too from wsl.config website by microsoft:
# Specify a custom Linux kernel to use with your installed distros. The default kernel used can be found at https://github.com/microsoft/WSL2-Linux-Kernel
kernel=C:\\temp\\myCustomKernel
(besides wsl kernel, theres also custom one from this https://github.com/microsoft/WSL2-Linux-Kernel )
or system32/lxss/tools/kernel is enough for waydroid on wsl?
;
alright, im gonna try something like bazzite. just asking, with this kernel instruction, why does it not also includes binder_linux modules?
https://github.com/choff/anbox-modules?search=1 from https://github.com/waydroid/waydroid/issues/590 and https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install
(this should be written in guide after the installation section, if binder is missing, why none in docs?)
;
alright, even with distrobox, the binder_modules is needed.
how do I solve this in wsl, do I use my default kernel from wsl? the one from waydroid that is in System32 doesnt seems to be solving this problem inside wsl /lib/modules/kernel directory?
```
logs:
sudo dkms install anbox-ashmem/1
sudo dkms install anbox-binder/1
```
doesn't work with error:
```
~/anbox-modules$  sudo dkms install anbox-ashmem/1
 sudo dkms install anbox-binder/1
Error! Your kernel headers for kernel 5.15.167.4-microsoft-standard-WSL2 cannot be found at /lib/modules/5.15.167.4-microsoft-standard-WSL2/build or /lib/modules/5.15.167.4-microsoft-standard-WSL2/source.
Please install the linux-headers-5.15.167.4-microsoft-standard-WSL2 package or use the --kernelsourcedir option to tell DKMS where it's located.
```
```
logs:
~$ sudo waydroid init
[15:38:29] Failed to load binder driver
[15:38:29] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
[15:38:29] ERROR: Binder node "binder" for waydroid not found
[15:38:29] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ sudo waydroid log
OSError: Binder node "binder" for waydroid not found

(006154) [11:27:22] ERROR: Action "init" needs root access
(006154) [11:27:22] See also: <https://github.com/waydroid>
(006154) [11:27:22] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(006155) [11:27:26] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006155) [11:27:26] *** output passed to waydroid stdout, not to this log ***
(006161) [11:31:05] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(006161) [11:31:05] Failed to load binder driver
(006161) [11:31:05] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(006161) [11:31:05] ERROR: Binder node "binder" for waydroid not found
(006161) [11:31:05] See also: <https://github.com/waydroid>
(006161) [11:31:05] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 123, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 41, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003217) [15:38:22] ERROR: Action "init" needs root access
(003217) [15:38:22] See also: <https://github.com/waydroid>
(003217) [15:38:22] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(003220) [15:38:28] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003220) [15:38:29] Failed to load binder driver
(003220) [15:38:29] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003220) [15:38:29] ERROR: Binder node "binder" for waydroid not found
(003220) [15:38:29] See also: <https://github.com/waydroid>
(003220) [15:38:29] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 123, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 41, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003224) [15:38:50] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003224) [15:38:50] *** output passed to waydroid stdout, not to this log ***
```
```
sudo systemctl status waydroid-container.service
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled;>
     Active: active (running) since Wed 2025-01-29 12:07:02 WIB; 3h 38min ago
   Main PID: 482 (waydroid)
      Tasks: 1 (limit: 3564)
     Memory: 24.3M ()
     CGroup: /system.slice/waydroid-container.service
             └─482 /usr/bin/python3 /usr/bin/waydroid -w container start

Jan 29 12:06:59 LAPTOP-T44S8GEB-Adhjie systemd[1]: Starting waydroid-container.se>
Jan 29 12:07:02 LAPTOP-T44S8GEB-Adhjie systemd[1]: Started waydroid-container.ser>
...skipping...
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled;>
     Active: active (running) since Wed 2025-01-29 12:07:02 WIB; 3h 38min ago
   Main PID: 482 (waydroid)
      Tasks: 1 (limit: 3564)
     Memory: 24.3M ()
     CGroup: /system.slice/waydroid-container.service
             └─482 /usr/bin/python3 /usr/bin/waydroid -w container start

Jan 29 12:06:59 LAPTOP-T44S8GEB-Adhjie systemd[1]: Starting waydroid-container.se>
Jan 29 12:07:02 LAPTOP-T44S8GEB-Adhjie systemd[1]: Started waydroid-container.ser>
~
~
 ESCOD
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled;>
     Active: active (running) since Wed 2025-01-29 12:07:02 WIB; 3h 38min ago
   Main PID: 482 (waydroid)
      Tasks: 1 (limit: 3564)
     Memory: 24.3M ()
     CGroup: /system.slice/waydroid-container.service
             └─482 /usr/bin/python3 /usr/bin/waydroid -w container start

Jan 29 12:06:59 LAPTOP-T44S8GEB-Adhjie systemd[1]: Starting waydroid-container.se>
Jan 29 12:07:02 LAPTOP-T44S8GEB-Adhjie systemd[1]: Started waydroid-container.ser>
~
~
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ sudo waydroid log
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 123, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 41, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003217) [15:38:22] ERROR: Action "init" needs root access
(003217) [15:38:22] See also: <https://github.com/waydroid>
(003217) [15:38:22] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(003220) [15:38:28] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003220) [15:38:29] Failed to load binder driver
(003220) [15:38:29] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003220) [15:38:29] ERROR: Binder node "binder" for waydroid not found
(003220) [15:38:29] See also: <https://github.com/waydroid>
(003220) [15:38:29] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 123, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 41, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003224) [15:38:50] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003224) [15:38:50] *** output passed to waydroid stdout, not to this log ***
(003238) [15:45:08] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003238) [15:45:08] Failed to load binder driver
(003238) [15:45:08] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.167.4-microsoft-standard-WSL2
(003238) [15:45:08] ERROR: Binder node "binder" for waydroid not found
(003238) [15:45:08] See also: <https://github.com/waydroid>
(003238) [15:45:08] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 123, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 41, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003246) [15:45:28] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003246) [15:45:28] *** output passed to waydroid stdout, not to this log ***
^Cadhjie@LAPTOP-T44S8GEB-Adhjie:~sudo waydroid logcat > ~/waydroid-logcat.txtxt
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ grep -i -e android -e memfd -e ashmem "/boot/config-$(uname -r)"
grep: /boot/config-5.15.167.4-microsoft-standard-WSL2: No such file or directory
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ zgrep -i -e android -e memfd -e ashmem /proc/config.gz
# Android
# CONFIG_ANDROID is not set
# end of Android
CONFIG_MEMFD_CREATE=y
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
adhjie@LAPTOP-T44S8GEB-Adhjie:~$ uname -a
Linux LAPTOP-T44S8GEB-Adhjie 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thebigG** [comment]
@Walker088 Your solution worked for pop-os 22.04. Thanks!

For anyone who is able to install it, but then waydroid does not seem to be able to start: make sure you are running wayland and NOT X11.

**Comment by Shaun-York** [comment]
Got this error on Pop!_OS 22.04 LTS using Wayland. I just installed the modules.  https://github.com/choff/anbox-modules

Fixed the issue.

**Comment by roshanshah18** [comment]
`
1 . sudo apt install dkms 

2. git clone https://github.com/choff/anbox-modules

 3. cd anbox-modules
 sudo ./INSTALL.sh

4. cd ~
  echo "nft_xfrm" | sudo tee -a /etc/modules-load.d/waydroid.confnft_xfrm
 5. sudo modprobe nft_xfrm

`
It worked for me,  you should try it too.
